name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:          
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Lexicon.WPF.Converters/Lexicon.WPF.Converters.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Lexicon.Xamarin.Converters/Lexicon.Xamarin.Converters.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Lexicon.WPF.AttachableProperties/Lexicon.WPF.AttachableProperties.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Lexicon.WPF.MVVM/Lexicon.WPF.MVVM.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Lexicon.Xamarin.MVVM/Lexicon.Xamarin.MVVM.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
